'use client';
import {useEffect,useState} from 'react';import type {Project,ProjectImage} from '@/lib/projects';
const json={'content-type':'application/json'};
export default function AdminPanel({initialProjects}:{initialProjects:Project[]}){const[projects,setProjects]=useState(initialProjects);const[selected,setSelected]=useState<number|''>(initialProjects[0]?.id||'');const[status,setStatus]=useState('');const[diagnostic,setDiagnostic]=useState('Loading Instagram status…');const current=projects.find(p=>p.id===selected);
 useEffect(()=>{fetch('/api/admin/instagram').then(r=>r.json()).then(d=>setDiagnostic(d.lastSuccess?`Last successful sync: ${new Date(d.lastSuccess).toLocaleString()}${d.status?.ok===false?` · Latest attempt failed: ${d.status.message}`:''}`:'No successful Instagram sync yet.')).catch(()=>setDiagnostic('Instagram diagnostic unavailable.'))},[]);
 async function refresh(message:string){const r=await fetch('/api/admin/projects');if(r.ok){const next=await r.json();setProjects(next);if(!next.some((p:Project)=>p.id===selected))setSelected(next[0]?.id||'');}setStatus(message);}
 async function request(url:string,options:RequestInit,message:string){setStatus('Saving…');const r=await fetch(url,options);const d=await r.json();if(!r.ok){setStatus(d.error||'Unable to save');return false}await refresh(message);return true}
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const ok=await request('/api/admin/projects',{method:'POST',headers:json,body:JSON.stringify(projectBody(f))},'Project created.');if(ok)e.currentTarget.reset()}
 async function update(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!current)return;const f=new FormData(e.currentTarget);await request('/api/admin/projects',{method:'PUT',headers:json,body:JSON.stringify({id:current.id,...projectBody(f)})},'Project updated.');}
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);await request('/api/admin/upload',{method:'POST',body:fd},'Images uploaded.');form.reset();}
 async function removeProject(){if(!current||!confirm(`Delete “${current.title}” and all of its images?`))return;await request(`/api/admin/projects?id=${current.id}`,{method:'DELETE'},'Project deleted.');}
 async function removeImage(image:ProjectImage){if(!confirm('Delete this image?'))return;await request(`/api/admin/images?id=${image.id}`,{method:'DELETE'},'Image deleted.');}
 async function editAlt(image:ProjectImage){const alt=prompt('Alt text',image.alt_text);if(!alt||alt===image.alt_text)return;await request('/api/admin/images',{method:'PATCH',headers:json,body:JSON.stringify({id:image.id,alt})},'Alt text updated.');}
 async function moveProject(id:number,direction:number){const at=projects.findIndex(p=>p.id===id),to=at+direction;if(to<0||to>=projects.length)return;const next=[...projects];[next[at],next[to]]=[next[to],next[at]];setProjects(next);await request('/api/admin/projects',{method:'PATCH',headers:json,body:JSON.stringify({ids:next.map(p=>p.id)})},'Project order updated.');}
 async function moveImage(id:number,direction:number){if(!current)return;const at=current.images.findIndex(i=>i.id===id),to=at+direction;if(to<0||to>=current.images.length)return;const images=[...current.images];[images[at],images[to]]=[images[to],images[at]];setProjects(projects.map(p=>p.id===current.id?{...p,images}:p));await request('/api/admin/images',{method:'PATCH',headers:json,body:JSON.stringify({projectId:current.id,ids:images.map(i=>i.id)})},'Image order updated.');}
 return <><div className="adminGrid"><section><h2>Create project</h2><ProjectForm onSubmit={create}/><h2 className="adminSubhead">Project order</h2><div className="adminList">{projects.map((p,i)=><div key={p.id}><button className="adminSelect" onClick={()=>setSelected(p.id)}><strong>{p.title}</strong><span>{p.published?'Published':'Draft'} · {p.images.length} images</span></button><span className="orderControls"><button onClick={()=>moveProject(p.id,-1)} disabled={i===0} aria-label={`Move ${p.title} up`}>↑</button><button onClick={()=>moveProject(p.id,1)} disabled={i===projects.length-1} aria-label={`Move ${p.title} down`}>↓</button></span></div>)}</div></section><section>{current?<><h2>Edit project</h2><ProjectForm key={current.id} project={current} onSubmit={update}/><button className="danger" onClick={removeProject}>Delete project</button><h2 className="adminSubhead">Images</h2><form onSubmit={upload} className="adminForm"><input type="hidden" name="projectId" value={current.id}/><label>Select images<input name="files" type="file" accept="image/jpeg,image/png,image/webp" multiple required/></label><label>Shared alt text (optional)<input name="alt" placeholder="A concise description of the image"/></label><button className="btn">Upload images</button></form><div className="imageAdmin">{current.images.map((image,i)=><div key={image.id}><img src={image.public_url} alt={image.alt_text}/><p>{image.alt_text}</p><div><button onClick={()=>moveImage(image.id,-1)} disabled={i===0}>Move up</button><button onClick={()=>moveImage(image.id,1)} disabled={i===current.images.length-1}>Move down</button><button onClick={()=>editAlt(image)}>Edit alt text</button><button onClick={()=>removeImage(image)}>Delete</button></div>{i===0&&<span className="coverLabel">Cover image</span>}</div>)}</div></>:<p>Select or create a project.</p>}</section></div><aside className="adminDiagnostic"><strong>Instagram</strong><span>{diagnostic}</span></aside>{status&&<p className="adminStatus" role="status">{status}</p>}</>}
function projectBody(f:FormData){return{title:f.get('title'),slug:f.get('slug'),service:f.get('service'),location:f.get('location'),description:f.get('description'),year:f.get('year')||undefined,featured:f.get('featured')==='on',published:f.get('published')==='on'}}
function ProjectForm({project,onSubmit}:{project?:Project;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={onSubmit} className="adminForm"><label>Project title<input name="title" defaultValue={project?.title} required/></label><label>URL slug<input name="slug" defaultValue={project?.slug} pattern="[a-z0-9-]+" required/></label><label>Service<input name="service" defaultValue={project?.service} required/></label><label>Location<input name="location" defaultValue={project?.location} required/></label><label>Year<input name="year" type="number" defaultValue={project?.year||new Date().getFullYear()}/></label><label>Description<textarea name="description" rows={5} defaultValue={project?.description}/></label><label className="check"><input name="featured" type="checkbox" defaultChecked={Boolean(project?.featured)}/> Feature on home page</label><label className="check"><input name="published" type="checkbox" defaultChecked={project?Boolean(project.published):true}/> Published</label><button className="btn">{project?'Save changes':'Create project'}</button></form>}
