import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {requireAdmin} from "@/lib/auth";
import {getEnv} from "@/lib/cloudflare";
import {listProjects} from "@/lib/projects";
const schema=z.object({title:z.string().min(2),slug:z.string().regex(/^[a-z0-9-]+$/),service:z.string().min(2),location:z.string().min(2),description:z.string().default(""),year:z.coerce.number().int().min(2000).max(2100).optional(),featured:z.boolean().default(false),published:z.boolean().default(true)});
const error=(e:any,message:string)=>NextResponse.json({error:e?.issues?.[0]?.message||e?.message||message},{status:e?.message==="UNAUTHORISED"?401:400});
export async function GET(){try{await requireAdmin();return NextResponse.json(await listProjects(true));}catch(e){return error(e,"Unauthorised");}}
export async function POST(req:NextRequest){try{await requireAdmin();const body=schema.parse(await req.json());const {DB}=getEnv();const next=await DB.prepare("SELECT COALESCE(MAX(sort_order),0)+10 value FROM projects").first<{value:number}>();const result=await DB.prepare(`INSERT INTO projects(slug,title,service,location,description,year,featured,published,sort_order) VALUES(?,?,?,?,?,?,?,?,?)`).bind(body.slug,body.title,body.service,body.location,body.description,body.year??null,body.featured?1:0,body.published?1:0,next?.value??10).run();return NextResponse.json({ok:true,id:result.meta.last_row_id});}catch(e){return error(e,"Unable to save project");}}
export async function PUT(req:NextRequest){try{await requireAdmin();const raw=await req.json();const id=z.coerce.number().int().positive().parse(raw.id);const body=schema.parse(raw);const {DB}=getEnv();await DB.prepare(`UPDATE projects SET slug=?,title=?,service=?,location=?,description=?,year=?,featured=?,published=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(body.slug,body.title,body.service,body.location,body.description,body.year??null,body.featured?1:0,body.published?1:0,id).run();return NextResponse.json({ok:true});}catch(e){return error(e,"Unable to update project");}}
export async function PATCH(req:NextRequest){try{await requireAdmin();const body=z.object({ids:z.array(z.number().int().positive()).min(1)}).parse(await req.json());const {DB}=getEnv();await DB.batch(body.ids.map((id,index)=>DB.prepare("UPDATE projects SET sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind((index+1)*10,id)));return NextResponse.json({ok:true});}catch(e){return error(e,"Unable to reorder projects");}}
export async function DELETE(req:NextRequest){try{await requireAdmin();const id=z.coerce.number().int().positive().parse(new URL(req.url).searchParams.get("id"));const env=getEnv();const {results}=await env.DB.prepare("SELECT object_key FROM project_images WHERE project_id=?").bind(id).all<{object_key:string}>();await Promise.all(results.filter((x:{object_key:string})=>!x.object_key.startsWith("seed/")).map((x:{object_key:string})=>env.PORTFOLIO_BUCKET.delete(x.object_key)));await env.DB.prepare("DELETE FROM projects WHERE id=?").bind(id).run();return NextResponse.json({ok:true});}catch(e){return error(e,"Unable to delete project");}}
