import Link from "next/link";import {RevealImage} from "@/components/site";import {imgs} from "@/lib/images";import InstagramFeed from "@/components/instagram-feed";import {WorkSlider} from "@/components/work-slider";
const services=[["02","Glass splashbacks","Durable custom glass for kitchens, laundries and commercial interiors."],["03","Pool fencing","Clear safety boundaries that preserve open views."],["04","Glass balustrades","Low-profile glazing for stairs, balconies and decks."],["05","Custom mirrors","Made-to-measure mirrors for bathrooms and feature spaces."],["06","Windows and replacements","New glass, repairs and replacement panels."],["07","Commercial shopfronts","Custom glazing for retail, hospitality and offices."]];
export default function Home(){return <main>
 <section className="hero"><RevealImage src="/projects/apex20.jpeg" alt="Curved frameless glass pool fencing in a landscaped garden" className="heroImage" priority/><div className="heroCopy"><div className="eyebrow">Residential and commercial glazing · Newcastle NSW</div><h1>More light.<br/><span className="serif">Less interruption.</span></h1><p className="lead">Custom glazing measured, supplied and installed across Newcastle, Lake Macquarie, the Central Coast and the Hunter Valley.</p><div className="actions"><Link className="btn" href="/contact">Request a quote</Link><Link className="textLink" href="/services">Explore our services</Link></div></div></section>
 <section className="section"><div className="shell introGrid"><h2 className="sectionTitle">Beautiful glasswork should feel like part of the architecture.</h2><div><p className="copy">Apex Frameless Glass creates custom installations that improve light, openness and function without overwhelming the room. Every project is carefully measured, clearly communicated and cleanly installed.</p><div className="processMini"><div><span>01</span><span>Measure carefully</span></div><div><span>02</span><span>Prepare precisely</span></div><div><span>03</span><span>Install cleanly</span></div></div></div></div></section>
 <WorkSlider/>
 <section className="section homeServices"><div className="shell"><div className="eyebrow">What we do</div><div className="feature"><RevealImage src={imgs.detail} alt="Frameless shower detail"/><div><h2 className="sectionTitle">Precision glasswork for every space.</h2><p className="copy">From frameless bathrooms to outdoor balustrades and pool fencing, every installation is measured for the site and finished with care.</p><Link className="textLink" href="/services">Explore all services</Link></div></div><div className="serviceRows homeServiceRows">{services.map(([n,name,d])=><Link href="/services" className="serviceRow" key={name}><span className="num">{n}</span><span className="serviceName">{name}</span><span className="muted">{d}</span><span aria-hidden="true">↗</span></Link>)}</div></div></section>
 <section className="section about"><div className="shell introGrid"><h2 className="sectionTitle">Experience you can see in the finish.</h2><div><p className="copy">Apex Frameless Glass is a Newcastle-based glazing company with more than 40 years of combined industry experience. The team focuses on reliable service, accurate measuring and workmanship that holds up in the details.</p><div className="statGrid"><div>40+ years combined experience</div><div>Licensed and fully insured</div><div>Free measure and quotes</div></div></div></div></section><InstagramFeed/>
 <section className="quoteBand"><div className="shell quoteBandInner"><div><div className="eyebrow">Planning a glazing project?</div><h2>Start with a clear conversation.</h2><p>Tell us about the space, your location and what you need. We’ll help clarify the next step.</p></div><Link className="btn lightBtn" href="/contact">Request a free measure and quote</Link></div></section>
 </main>}
