'use client';
import {useRef,useState} from 'react';

const endpoint='https://api.web3forms.com/submit';

export default function QuoteForm(){
 const[status,setStatus]=useState('');const[sending,setSending]=useState(false);const formRef=useRef<HTMLFormElement>(null);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(sending)return;setSending(true);setStatus('Sending your project details…');try{const form=new FormData(e.currentTarget);const response=await fetch(endpoint,{method:'POST',body:form});const result=await response.json() as {success?:boolean;message?:string};if(!response.ok||!result.success)throw new Error(result.message||'Please check the form and try again.');setStatus('Thanks — your project details have been sent. The Apex team will be in touch.');formRef.current?.reset();}catch(error){setStatus(error instanceof Error?error.message:'Unable to send your request. Please try again.');}finally{setSending(false)}}
 return <form ref={formRef} action={endpoint} method="POST" onSubmit={submit} className="formGrid" aria-busy={sending}><input type="hidden" name="access_key" value="665afa0a-7340-401e-877d-bae669d124b5"/><input type="hidden" name="subject" value="New Apex Frameless Glass quote request"/><input type="hidden" name="from_name" value="Apex Frameless Glass website"/><div className="honeypot" aria-hidden="true"><label>Leave this empty<input type="checkbox" name="botcheck" tabIndex={-1}/></label></div><div className="field"><label htmlFor="name">Full name</label><input id="name" name="name" autoComplete="name" required/></div><div className="field"><label htmlFor="email">Email address</label><input id="email" name="email" type="email" autoComplete="email" required/></div><div className="field"><label htmlFor="phone">Phone number</label><input id="phone" name="phone" type="tel" autoComplete="tel" required/></div><div className="field"><label htmlFor="suburb">Project suburb</label><input id="suburb" name="suburb" autoComplete="address-level2"/></div><div className="field"><label htmlFor="service">Service required</label><select id="service" name="service" required><option value="">Select a service</option><option>Shower screen</option><option>Splashback</option><option>Pool fencing</option><option>Balustrade</option><option>Mirror</option><option>Window replacement</option><option>Commercial shopfront</option></select></div><div className="field"><label htmlFor="project_type">Project type</label><select id="project_type" name="project_type"><option>Residential</option><option>Commercial</option></select></div><div className="field full"><label htmlFor="message">Tell us about the project</label><textarea id="message" name="message" minLength={10} placeholder="What would you like installed, and when are you hoping to start?" required/></div><div className="field full"><label htmlFor="measurements">Approximate measurements <span>(optional)</span></label><input id="measurements" name="measurements" placeholder="Width × height, if known"/></div><div className="field full submitField"><button className="btn" type="submit" disabled={sending}>{sending?'Sending…':'Send project details'}</button><p className="formStatus" role="status" aria-live="polite">{status}</p><small>By submitting, you agree that Apex may contact you about this enquiry.</small></div></form>
}
